<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<!-- Localization -->
	<ItemGroup>
		<None Remove="Localization\*.hjson" />
		<Content Include="Localization\*.hjson">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
